/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}', './node_modules/@tremor/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  // Tremor charts build palette classes (stroke-lime-500, ...) at runtime,
  // so they must be safelisted — Tailwind can't see them statically.
  safelist: [
    {
      pattern:
        /^(bg|text|border|ring|stroke|fill|decoration)-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/,
      variants: ['hover', 'dark'],
    },
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#c0f500',
        'tertiary-fixed': '#e3e2e2',
        surface: '#131313',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#a8d700',
        'on-tertiary-fixed': '#1a1c1c',
        'on-secondary-fixed': '#1a1c19',
        'on-secondary': '#2f312e',
        'inverse-surface': '#e5e2e1',
        'secondary-container': '#484a46',
        'on-tertiary-container': '#646464',
        'on-primary': '#273500',
        'on-primary-fixed': '#161f00',
        'surface-tint': '#a8d700',
        'secondary-fixed': '#e3e3de',
        'error-container': '#93000a',
        error: '#ffb4ab',
        'primary-fixed': '#c0f500',
        'surface-container': '#201f1f',
        'surface-container-highest': '#353534',
        'inverse-on-surface': '#313030',
        'on-surface-variant': '#c4caac',
        'surface-bright': '#3a3939',
        'on-error': '#690005',
        'inverse-primary': '#4f6600',
        'on-primary-fixed-variant': '#3b4d00',
        'surface-container-high': '#2a2a2a',
        'surface-dim': '#131313',
        'secondary-fixed-dim': '#c6c7c2',
        outline: '#8e9479',
        'tertiary-fixed-dim': '#c7c6c6',
        'surface-variant': '#353534',
        secondary: '#c6c7c2',
        'on-primary-container': '#546d00',
        'on-background': '#e5e2e1',
        primary: '#ffffff',
        'on-secondary-container': '#b8b9b4',
        'tertiary-container': '#e3e2e2',
        tertiary: '#ffffff',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-fixed-variant': '#454744',
        'on-tertiary-fixed-variant': '#464747',
        'on-tertiary': '#2f3131',
        'on-surface': '#e5e2e1',
        'outline-variant': '#434933',
        'surface-container-low': '#1c1b1b',
        background: '#131313',
        // Tremor chart internals (axis, grid, dots) — same object, no duplicate key.
        tremor: {
          border: '#2a2a2a',
          content: '#a8b09a',
          'content-emphasis': '#e5e2e1',
          label: '#a8b09a',
          background: '#131313',
        },
        'dark-tremor': {
          border: '#2a2a2a',
          content: '#a8b09a',
          'content-emphasis': '#e5e2e1',
          label: '#a8b09a',
          background: '#131313',
        },
      },
      fontFamily: {
        jersey: ["'Jersey 15'", 'monospace', 'sans-serif'],
        grotesk: ["'Space Grotesk'", 'sans-serif'],
        jakarta: ["'Plus Jakarta Sans'", 'sans-serif'],
        'hud-label': ["'JetBrains Mono'", 'monospace'],
        'hud-code': ["'JetBrains Mono'", 'monospace'],
        'headline-md': ["'Space Grotesk'", 'sans-serif'],
        'headline-lg': ["'Space Grotesk'", 'sans-serif'],
        'headline-sm': ["'Space Grotesk'", 'sans-serif'],
        'headline-xl': ["'Space Grotesk'", 'sans-serif'],
        'body-lg': ["'Plus Jakarta Sans'", 'sans-serif'],
        'body-md': ["'Plus Jakarta Sans'", 'sans-serif'],
        'body-sm': ["'Plus Jakarta Sans'", 'sans-serif'],
      },
      fontSize: {
        'hud-label': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'hud-code': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'hud-metric': ['22px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['15px', { lineHeight: '24px' }],
        'body-sm': ['13px', { lineHeight: '20px' }],
      },
      spacing: {
        'margin-mobile': '1rem',
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter-lg': '2rem',
      },
      borderRadius: {
        DEFAULT: '0px',
      },
      boxShadow: {
        'brutal-lime': '4px 4px 0px #c0f500',
        'brutal-white': '4px 4px 0px #ffffff',
        'brutal-white-lg': '6px 6px 0px #ffffff',
        'brutal-lime-lg': '6px 6px 0px #c0f500',
        'brutal-dark': '4px 4px 0px #000000',
      },
    },
  },
  plugins: [],
}

