# Generated by Django 6.1.1 on 2026-09-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
