# Generated by Django 6.1.1 on 2026-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_transaction_lead_transaction_title'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='crm.lead'),
        ),
    ]
