# Generated by Django 6.1.1 on 2026-09-22 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
