# Generated by Django 6.1.1 on 2026-09-18 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('webdev', 'IamFit Web Development'), ('gamedev', 'IamFit GameDev'), ('store', 'IamFit Store'), ('labs', 'IamFit Labs'), ('other', 'Other')], default='webdev', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('demo_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_projects', to='crm.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='projects_bu_owner_i_7c4377_idx'), models.Index(fields=['owner', '-created_at'], name='projects_bu_owner_i_0f5ea2_idx')],
            },
        ),
    ]
